### PR TITLE
Add LOGO

### PR DESCRIPTION
**Pull request by rijal10**
hi sir
I have edited your readme.md, and I put my logo on your description on this project. and so on you can also check my commits. if everything ok please merge to your readme.md

Warm regards :)
rijal10

### CODE REVIEW

**Review by jamesstar89 — COMMENTED** [review]
Can we make the following changes please:
1. Squash to single commit
2. Rename image format to logo-250px.png thank you

**Comment by rijal10** [comment]
Sir!
I do not understand with point number one, because I am not too familiar with github!
and with point number two I have fixed it!

Warm regards :)
rijal10

**Comment by jamesstar89** [comment]
Hi @rijal10, might be better if I make the changes and commit from my side. Thanks!

**Comment by rijal10** [comment]
Thank you sir!:
proud to work with you, I can not wait to see my work posted in this great app! 👍🥇🥇🥇

**Pull request closed without merging**
